import "./globals.css";
import NavBar from "../components/ui/Navbar";
import ProtectedRoute from "../components/auth/ProtectedRoute"; // Import ProtectedRoute

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {/* Wrap the children with ProtectedRoute */}
        <ProtectedRoute>{children}</ProtectedRoute>
      </body>
    </html>
  );
}
